### ISSUE TITLE
【上游问题】-Xcomp选项fastdebug版本运行compiler/loopopts/TestRangeCheckPredicatesControl.java失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#524]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/159161?tab=1

```
java.lang.OutOfMemoryError: Java heap space
	at compiler.loopopts.TestRangeCheckPredicatesControl.test2(TestRangeCheckPredicatesControl.java:98)
	at compiler.loopopts.TestRangeCheckPredicatesControl.main(TestRangeCheckPredicatesControl.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "MainThread"
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.lang.StringBuffer
	at com.sun.javatest.regtest.agent.MainWrapper.handleTestException(MainWrapper.java:94)
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:81)
```

**Comment by zhaoyuanfang1** [comment]
dragonwell复现概率：5/1000

**Comment by zhaoyuanfang1** [comment]
dragonwell复现概率：5/1000
Temurin复现概率：2/1000
@sendaoYan

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/12723579
