### ISSUE TITLE
[上游问题]sanity/MismatchedWhiteBox/WhiteBox.java报错Failed to find sun/hotspot/WhiteBox$WhiteBoxPermission.class

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#624]
```log
ACTION: driver -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed to find sun/hotspot/WhiteBox$WhiteBoxPermission.class
REASON: User specified action: run driver ClassFileInstaller sun.hotspot.WhiteBox 
TIME:   0.133 seconds
messages:
command: driver ClassFileInstaller sun.hotspot.WhiteBox
reason: User specified action: run driver ClassFileInstaller sun.hotspot.WhiteBox 
started: Mon Jun 19 17:39:28 CST 2023
Mode: othervm
Additional options from @modules: --add-modules java.base --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
finished: Mon Jun 19 17:39:28 CST 2023
elapsed time (seconds): 0.133
configuration:
Boot Layer
  add modules: java.base                   
  add exports: java.base/jdk.internal.misc ALL-UNNAMED

STDOUT:
STDERR:
java.lang.RuntimeException: Failed to find sun/hotspot/WhiteBox$WhiteBoxPermission.class
        at ClassFileInstaller.writeClassToDisk(ClassFileInstaller.java:240)
        at ClassFileInstaller.writeClassToDisk(ClassFileInstaller.java:227)
        at ClassFileInstaller.writeClassToDisk(ClassFileInstaller.java:224)
        at ClassFileInstaller.main(ClassFileInstaller.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Failed to find sun/hotspot/WhiteBox$WhiteBoxPermission.class
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Failed to find sun/hotspot/WhiteBox$WhiteBoxPermission.class
rerun:
cd /home/yansendao/git/dragonwell11/tmp/scratch && \
DISPLAY=:7 \
HOME=/home/yansendao \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/home/yansendao/git/dragonwell11/tmp/classes/sanity/MismatchedWhiteBox/WhiteBox.d:/home/yansendao/git/dragonwell11/test/hotspot/jtreg/sanity/MismatchedWhiteBox:/home/yansendao/git/dragonwell11/tmp/classes/test/lib:/home/yansendao/git/dragonwell11/test/lib:/home/yansendao/software/jdk/jtreg-6/lib/javatest.jar:/home/yansendao/software/jdk/jtreg-6/lib/jtreg.jar \
    /home/yansendao/software/jdk/2023-02/dragonwell-11.0.18.14+9-GA/bin/java \
        -Dtest.vm.opts= \
        -Dtest.tool.vm.opts= \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/home/yansendao/software/jdk/2023-02/dragonwell-11.0.18.14+9-GA \
        -Dcompile.jdk=/home/yansendao/software/jdk/2023-02/dragonwell-11.0.18.14+9-GA \
        -Dtest.timeout.factor=1.0 \
        -Dtest.root=/home/yansendao/git/dragonwell11/test/hotspot/jtreg \
        -Dtest.name=sanity/MismatchedWhiteBox/WhiteBox.java \
        -Dtest.file=/home/yansendao/git/dragonwell11/test/hotspot/jtreg/sanity/MismatchedWhiteBox/WhiteBox.java \
        -Dtest.src=/home/yansendao/git/dragonwell11/test/hotspot/jtreg/sanity/MismatchedWhiteBox \
        -Dtest.src.path=/home/yansendao/git/dragonwell11/test/hotspot/jtreg/sanity/MismatchedWhiteBox:/home/yansendao/git/dragonwell11/test/lib \
        -Dtest.classes=/home/yansendao/git/dragonwell11/tmp/classes/sanity/MismatchedWhiteBox/WhiteBox.d \
        -Dtest.class.path=/home/yansendao/git/dragonwell11/tmp/classes/sanity/MismatchedWhiteBox/WhiteBox.d:/home/yansendao/git/dragonwell11/tmp/classes/test/lib \
        -Dtest.modules=java.base/jdk.internal.misc \
        --add-modules java.base \
        --add-exports java.base/jdk.internal.misc=ALL-UNNAMED \
        com.sun.javatest.regtest.agent.MainWrapper /home/yansendao/git/dragonwell11/tmp/sanity/MismatchedWhiteBox/WhiteBox.d/driver.2.jta sun.hotspot.WhiteBox

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Failed to find sun/hotspot/WhiteBox$WhiteBoxPermission.class
```

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8236045

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk11u/pull/75

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk11u-dev/pull/1963

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14145548?file=3dc64038c6e343e9444c7246d7c87c864b7ba598
