### ISSUE TITLE
[自研] aarch64平台compiler/c2/aarch64/TestFarJump.java运行报错

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#666]
test command：

```bash
jtreg -va -nr -w tmp test/hotspot/jtreg/compiler/c2/aarch64/TestFarJump.java
```

result:
```log
STDOUT:
Command line: [/home/yansendao/software/jdk/2023-09/dragonwell-11.0.20.16+8-GA/bin/java -cp /home/yansendao/git/dragonwell11/tmp/classes/compiler/c2/aarch64/TestFarJump.d:/home/yansendao/git/dragonwell11/test/hotspot/jtreg/compiler/c2/aarch64:/home/yansendao/git/dragonwell11/tmp/classes/test/lib:/home/yansendao/git/dragonwell11/test/lib:/home/yansendao/git/dragonwell11/tmp/classes:/home/yansendao/git/dragonwell11/test/hotspot/jtreg:/home/yansendao/software/jdk/jtreg-6/lib/javatest.jar:/home/yansendao/software/jdk/jtreg-6/lib/jtreg.jar -XX:-Inline -Xcomp -Xbatch -XX:+TieredCompilation -XX:+SegmentedCodeCache -XX:CompileOnly=compiler.c2.aarch64.TestFarJump::main -XX:ReservedCodeCacheSize=256M -XX:+UnlockDiagnosticVMOptions -XX:+PrintAssembly compiler.c2.aarch64.TestFarJump ]
[2023-09-06T09:38:27.077690Z] Gathering output for process 887987
STDERR:
java.lang.RuntimeException: Assembly output: exception Handler is not found
        at compiler.c2.aarch64.TestFarJump.runVM(TestFarJump.java:121)
        at compiler.c2.aarch64.TestFarJump.main(TestFarJump.java:127)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Assembly output: exception Handler is not found
JavaTest Message: shutting down test
```

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/d8857cb0-4d65-4a1d-943f-859ebbfb2eb6)

二进制链接：

oss://dragonwell/test-53/OpenJDK11U-jdk_aarch64_linux_dragonwell_2023-08-28-06-46.tar.gz

**Comment by lusou-zhangquan** [comment]
hsdis缺失导致PrintAssembly被disable，用例无法获取对应的反汇编指令信息

![image](https://github.com/dragonwell-project/dragonwell11/assets/88874527/c605683f-3ed5-4b7c-96c2-fe1e916365bc)

手动拷贝后用例pass

**Comment by sendaoYan** [comment]
执行测试用例时，需要先将hsdis-${arch}.so拷贝到jdk目录下
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/13943403?file=20113a600e8858663b83d5eee931568554bb53cf
