### ISSUE TITLE
[Bug][upstream]jdk/java/net/SctpSanity.java : Protocol not supported

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#707]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/238020?tab=1

【环境准备】
```
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-57/OpenJDK11U-jdk_x64_linux_dragonwell_2023-10-19-06-15.tar.gz
mkdir binary-download
tar xzvf binary.tar.gz -C binary-download
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-57/OpenJDK11U-testimage_x64_linux_dragonwell_2023-10-19-06-15.tar.gz -O test-image.tar.gz
make test-image
tar xzvf test-image.tar.gz -C test-image
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone https://github.com/dragonwell-project/dragonwell11.git jdk-repo -b wip_dragonwell_standard_merge_branch
native=-nativepath:./test-image/hotspot/jtreg/native
args=-Xmixed -ea -esa
test=jdk-repo/test/jdk/java/net/SctpSanity.java
jtreg -w tmp -nr -v:fail,error $native  $args $test
```

【对比测试】

dragonwell11 release版本同样错误.
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.20.16.8/Alibaba_Dragonwell_Standard_11.0.20.16.8_x64_linux.tar.gz -O binary.tar.gz

```
[root@VM20190228-137 d11-release]# java -version ; java -Xinternalversion
openjdk version "11.0.20.16" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.20.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.20.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20.16+8) for linux-amd64 JRE (11.0.20.16+8), built on Aug  8 2023 08:04:07 by "" with gcc 7.5.0

```
temurin11 同样错误.
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.21_9.tar.gz
```
[root@VM20190228-137 t11]# java -version; java -Xinternalversion
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21+9) for linux-amd64 JRE (11.0.21+9), built on Oct 17 2023 21:44:42 by "" with gcc 7.5.0

```

【用例日志】
[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/13111779/default.txt)

```
STDERR:

ACTION: main -- Failed. Execution failed: `main' threw exception: java.net.SocketException: Protocol not supported
REASON: User specified action: run main/othervm SctpSanity 1
TIME:   0.281 seconds
messages:
command: main SctpSanity 1
reason: User specified action: run main/othervm SctpSanity 1
Mode: othervm [/othervm specified]
Additional options from @modules: --add-modules jdk.sctp
elapsed time (seconds): 0.281
configuration:
Boot Layer
  add modules: jdk.sctp

STDOUT:
STDERR:
java.net.SocketException: Protocol not supported
        at jdk.sctp/sun.nio.ch.sctp.SctpNet.socket0(Native Method)
        at jdk.sctp/sun.nio.ch.sctp.SctpNet.socket(SctpNet.java:85)
        at jdk.sctp/sun.nio.ch.sctp.SctpChannelImpl.<init>(SctpChannelImpl.java:137)
        at jdk.sctp/com.sun.nio.sctp.SctpChannel.open(SctpChannel.java:170)
        at SctpSanity.testSctpChannel(SctpSanity.java:58)
        at SctpSanity.main(SctpSanity.java:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:829)

JavaTest Message: Test threw exception: java.net.SocketException: Protocol not supported
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.net.SocketException: Protocol not supported


```

【版本信息】
```
[root@VM20190228-137 d11]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20190228-137 5.10.134-14.al8.x86_64 #1 SMP Thu Apr 27 16:46:29 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       776Mi       1.6Gi       770Mi        12Gi        13Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
BIOS Model name:     pc-i440fx-2.1
Stepping:            4
CPU MHz:             2500.012
BogoMIPS:            5000.02
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-3
openjdk version "11.0.21.16" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.21.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.21.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21.16+8) for linux-amd64 JRE (11.0.21.16+8), built on Oct 19 2023 06:21:36 by "" with gcc 7.5.0


```

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8267938  https://github.com/openjdk/jdk/commit/bd31653e6f99d4337e4af1f7f138d688ec99c19d

**Comment by sendaoYan** [comment]
上游jdk17u已经合入  bd31653e6f99d4337e4af1f7f138d688ec99c19d
