### ISSUE TITLE
[TEST][upstream]sun/security/tools/jarsigner/warnings/NoTimestampTest.java随机失败 

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#708]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/238019?tab=2
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/238020?tab=2

【环境准备】
```
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-57/OpenJDK11U-jdk_x64_linux_dragonwell_2023-10-19-06-15.tar.gz
mkdir binary-download
tar xzvf binary.tar.gz -C binary-download
cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-57/OpenJDK11U-testimage_x64_linux_dragonwell_2023-10-19-06-15.tar.gz -O test-image.tar.gz
make test-image
tar xzvf test-image.tar.gz -C test-image
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -
git clone https://github.com/dragonwell-project/dragonwell11.git jdk-repo -b wip_dragonwell_standard_merge_branch
native=-nativepath:./test-image/hotspot/jtreg/native
args='-Xmixed -ea -esa'
test=jdk-repo/test/jdk/sun/security/tools/jarsigner/warnings/NoTimestampTest.java
dir="jt-work" ; rm -rf $dir ; mkdir -p $dir ; time seq 4000 | xargs -i -n 1 -P 1  bash -c "jtreg -w tmp -nr -v:fail,error $native  $args $test &> $dir/test-{}.log ; grep 'Test results: passed: 1' -L $dir/test-{}.log"
```

【对比测试】

手工测试, arm曾经在2000次左右开始出现. x64在3500次左右开始出现. 问题再release版本和上游都有这种情况.

dragonwell11 release版本同样错误.
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.20.16.8/Alibaba_Dragonwell_Standard_11.0.20.16.8_x64_linux.tar.gz -O binary.tar.gz

```
[root@VM20190228-137 d11-release]# java -version ; java -Xinternalversion
openjdk version "11.0.20.16" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.20.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.20.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20.16+8) for linux-amd64 JRE (11.0.20.16+8), built on Aug  8 2023 08:04:07 by "" with gcc 7.5.0

```
temurin11 同样错误.
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.21%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.21_9.tar.gz
```
[root@VM20190228-137 t11]# java -version; java -Xinternalversion
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21+9) for linux-amd64 JRE (11.0.21+9), built on Oct 17 2023 21:44:42 by "" with gcc 7.5.0

```

【用例日志】

[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/13172463/default.txt)

```
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2024-10-24).' missing from stdout/stderr
REASON: User specified action: run main NoTimestampTest
TIME:   6.693 seconds
messages:
command: main NoTimestampTest
reason: User specified action: run main NoTimestampTest
Mode: othervm
elapsed time (seconds): 6.693
configuration:
STDOUT:
Timezone =
Adding first.txt to unsigned.jar

Command line: [/disk1/d11-release/binary-download/bin/keytool -J-Duser.language=en -J-Duser.country=US -genkeypair -alias ca -keyalg RSA -keysize 2048 -keystore keystore.jks -storepass password -keypass password -dname CN=ca -ext bc:c]
[2023-10-25T16:00:02.850075Z] Gathering output for process 2830265

[2023-10-25T16:00:03.954521Z] Waiting for completion for process 2830265
[2023-10-25T16:00:03.954678Z] Waiting for completion finished for process 2830265
Command line: [/disk1/d11-release/binary-download/bin/keytool -J-Duser.language=en -J-Duser.country=US -genkeypair -alias alias -keyalg RSA -keysize 2048 -keystore keystore.jks -storepass password -keypass password -dname CN=alias]
[2023-10-25T16:00:03.955687Z] Gathering output for process 2830305

[2023-10-25T16:00:05.210183Z] Waiting for completion for process 2830305
[2023-10-25T16:00:05.210423Z] Waiting for completion finished for process 2830305
Command line: [/disk1/d11-release/binary-download/bin/keytool -J-Duser.language=en -J-Duser.country=US -certreq -alias alias -keystore keystore.jks -storepass password -keypass password -file alias.req]
[2023-10-25T16:00:05.216134Z] Gathering output for process 2830357

[2023-10-25T16:00:06.099367Z] Waiting for completion for process 2830357
[2023-10-25T16:00:06.099569Z] Waiting for completion finished for process 2830357
Command line: [/disk1/d11-release/binary-download/bin/keytool -J-Duser.language=en -J-Duser.country=US -gencert -alias ca -infile alias.req -outfile alias.cert -keystore keystore.jks -storepass password -keypass password -file alias.req -validity 365]
[2023-10-25T16:00:06.101656Z] Gathering output for process 2830394

[2023-10-25T16:00:07.034153Z] Waiting for completion for process 2830394
[2023-10-25T16:00:07.034441Z] Waiting for completion finished for process 2830394
Command line: [/disk1/d11-release/binary-download/bin/keytool -J-Duser.language=en -J-Duser.country=US -importcert -alias alias -keystore keystore.jks -storepass password -keypass password -file alias.cert]
[2023-10-25T16:00:07.035970Z] Gathering output for process 2830438
Certificate reply was installed in keystore

[2023-10-25T16:00:07.932357Z] Waiting for completion for process 2830438
[2023-10-25T16:00:07.932590Z] Waiting for completion finished for process 2830438
Cert expiration: Thu Oct 24 16:00:06 GMT 2024
Command line: [/disk1/d11-release/binary-download/bin/jarsigner -J-Duser.language=en -J-Duser.country=US -J-Duser.timezone= -keystore keystore.jks -storepass password -keypass password -signedjar signed.jar unsigned.jar alias]
[2023-10-25T16:00:08.232022Z] Gathering output for process 2830485
jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2024-10-25).

The signer certificate will expire on 2024-10-25.

[2023-10-25T16:00:09.132675Z] Waiting for completion for process 2830485
[2023-10-25T16:00:09.132909Z] Waiting for completion finished for process 2830485
[2023-10-25T16:00:09.133079Z] Waiting for completion for process 2830485
[2023-10-25T16:00:09.133184Z] Waiting for completion finished for process 2830485
STDERR:
 stdout: [jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2024-10-25).

The signer certificate will expire on 2024-10-25.
];
 stderr: []
 exitValue = 0

java.lang.RuntimeException: 'No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2024-10-24).' missing from stdout/stderr

        at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:163)
        at Test.checkSigning(Test.java:245)
        at NoTimestampTest.start(NoTimestampTest.java:95)
        at NoTimestampTest.main(NoTimestampTest.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:829)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 'No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2024-10-24).' missing from stdout/stderr

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: 'No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2024-10-24).' missing from stdout/stderr

```

【版本信息】
```
[root@VM20210305-10 dw11]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       506Mi       261Mi       0.0Ki        14Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "11.0.21.16" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.21.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-11.0.20.16+8-GA (build 11.0.21.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21.16+8) for linux-aarch64 JRE (11.0.21.16+8), built on Oct 19 2023 06:21:50 by "" with gcc 7.5.0


```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14505414?file=5951528f9b5712d5c693b23dc1761752ee786f61

**Comment by sendaoYan** [comment]
```bash
for i in `seq 10000` ; do echo -n "$i " ; date > test-$i.log ; jtreg -va -nr -w tmp-$i test/jdk/sun/security/tools/jarsigner/warnings/NoTimestampTest.java 2>&1 >> test-$.log ; if [[ 0 -ne $? ]] ; then break ; fi done ; echo "--"
```

**Comment by sendaoYan** [comment]
```bash
rm -rf alias.* first.txt keystore.jks signed.jar unsigned.jar
java -cp tmp/classes/sun/security/tools/jarsigner/warnings/NoTimestampTest.d:tmp/classes/test/lib NoTimestampTest
```

**Comment by sendaoYan** [comment]
dragonwell17 正常：

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/307638a8-b49d-4c5b-bab7-c32b4c2144bd)
