### ISSUE TITLE
[TESTBUG][upstream]CAInterop.java 运行失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#732]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/254887
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/254886
【环境准备】
```
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-56/OpenJDK11U-jdk_aarch64_linux_dragonwell_2023-11-20-06-42.tar.gz
wget  -O test-images.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-56/OpenJDK11U-testimage_aarch64_linux_dragonwell_2023-11-20-06-42.tar.gz

mkdir binary-download && mkdir test-images

tar xzvf binary.tar.gz -C binary-download
tar xzvf test-images.tar.gz -C test-images

cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -

wget -O jtreg.zip http://114.55.64.175:8666/compiler-ci-bucket/tools/jtreg-6.1.1.zip
unzip jtreg.zip
cd jtreg 
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
cd -

git clone https://github.com/dragonwell-project/dragonwell11.git jdk-repo -b wip_dragonwell_extended_merge_branch jdk-repo

native=-nativepath:./test-images/hotspot/jtreg/native
args='-Xmixed'
test=jdk-repo/test/jdk/security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java

jtreg  -nr -v:fail,error -w tmp  $args $native $test
```
共计33个子项:
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#actalisauthenticationrootca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#amazonrootca1
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#amazonrootca2
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#amazonrootca3
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#amazonrootca4
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#buypassclass2ca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#buypassclass3ca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#certignarootca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#comodoeccca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#comodorsaca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#entrustrootcaec1
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#entrustrootcag4
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#globalsigneccrootcar4
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#globalsignrootcar6
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#godaddyrootg2ca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootcar1
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootcar2
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootecccar3
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootecccar4
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#letsencryptisrgx1
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#microsoftecc2017
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#microsoftrsa2017
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#quovadisrootca1g3
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#quovadisrootca2g3
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#quovadisrootca3g3
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#sslrooteccca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#sslrootevrsaca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#sslrootrsaca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#starfieldrootg2ca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#teliasonerarootcav1
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#twcaglobalrootca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#usertrusteccca
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#usertrustrsaca

【对比测试】

用例为新增用例,release版本当时没有.

dragonwell11 release版本同样错误. 
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/11.0.20.16.8/Alibaba_Dragonwell_Extended_11.0.20.16.8_aarch64_linux.tar.gz

```
[root@VM20210305-10 bin]# ./java -version ; ./java -Xinternalversion
openjdk version "11.0.20.16" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.20.16+8-GA (build 11.0.20.16+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.20.16+8-GA (build 11.0.20.16+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.20.16+8) for linux-aarch64 JRE (11.0.20.16+8), built on Aug  8 2023 07:58:33 by "" with gcc 7.5.0
```

temurin11 同样错误.
wget http://114.55.64.175:8666/compiler-ci-bucket/openjdk/jdk-11.0.21-ga/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.21_9.tar.gz
```
[root@VM20210305-10 bin]# ./java -version ; ./java -Xinternalversion
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)
OpenJDK 64-Bit Server VM (11.0.21+9) for linux-aarch64 JRE (11.0.21+9), built on Oct 17 2023 21:44:42 by "" with gcc 7.5.0

```

【用例日志】
[完整日志.txt](https://github.com/dragonwell-releng/dragonwell-adoptium/files/13575336/default.txt)

```
STDOUT:
=====================================================
CONFIGURATION
=====================================================
http.proxyHost :null
http.proxyPort :null
https.proxyHost :null
https.proxyPort :null
https.socksProxyHost :null
https.socksProxyPort :null
jdk.certpath.disabledAlgorithms :MD2, MD5, SHA1 jdkCA & usage TLSServer, RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224, SHA1 usage SignedJAR & denyAfter 2019-01-01, include jdk.disabled.namedCurves
com.sun.security.enableCRLDP :false
ocsp.enable :true
=====================================================
STDERR:
java.lang.NullPointerException
        at ValidatePathWithURL.<init>(ValidatePathWithURL.java:64)
        at CAInterop.validate(CAInterop.java:551)
        at CAInterop.main(CAInterop.java:496)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.NullPointerException
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.NullPointerException
```

【版本信息】
```
[root@VM20210305-10 bin]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;./java -version; ./java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       472Mi       230Mi       0.0Ki        14Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "11.0.22.17" 2024-01-16
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.20.17+8-GA (build 11.0.22.17+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.20.17+8-GA (build 11.0.22.17+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.22.17+8) for linux-aarch64 JRE (11.0.22.17+8), built on Nov 20 2023 06:49:00 by "" with gcc 7.5.0


```

**Comment by sendaoYan** [comment]
源码里修复的bug：

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/65bcfd7a-8946-4dc9-a8c8-5932fb7d6128)

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14943137

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/15507911
