### ISSUE TITLE
两个dcmd/gc用例使用UseSerialGC选项运行失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#740]
job：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/257346?tab=3

test/hotspot/jtreg/serviceability/dcmd/gc/HeapDumpParallelTest.java
```
java.lang.RuntimeException: 'Dump heap objects in parallel' found in stdout 

	at jdk.test.lib.process.OutputAnalyzer.shouldNotContain(OutputAnalyzer.java:209)
	at HeapDumpParallelTest.checkAndVerify(HeapDumpParallelTest.java:69)
	at HeapDumpParallelTest.test(HeapDumpParallelTest.java:132)
	at HeapDumpParallelTest.main(HeapDumpParallelTest.java:118)
```

test/hotspot/jtreg/serviceability/dcmd/gc/HeapDumpCompressedTest.java#id0

```
Error occurred during initialization of VM
Multiple garbage collectors selected
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/15025883
