### ISSUE TITLE
[11.0.21.18.9][wisp]-Xcomp -XX:+UseCompactObjectHeaders选项运行com/alibaba/wisp/timer/TestSleepRPC.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#749]
job：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/259051?tab=3

```log
java.lang.RuntimeException: assertTrue: expected true, was false
	at jdk.testlibrary.Asserts.fail(Asserts.java:540)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
	at TestSleepRPC.main(TestSleepRPC.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)
```

[jtreg.stdout.log](https://github.com/dragonwell-project/dragonwell11/files/13722618/jtreg.stdout.log)

**Comment by yuleil** [comment]
该测试不稳定是测试本身的问题，但是和lilliput无关。

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/15199001?file=16960134feab06db300d6b7dfd6c0a1f60729ea8
