### ISSUE TITLE
[lilliput]fastdbug版本-Xcomp -XX:+UseCompactObjectHeaders选项运行serviceability/sa/TestJmapCore.java用例随机超时

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#753]
job链接：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/258155?tab=1

**Steps to Reproduce**
```bash
jtreg -va -nr -w tmp-compactHeader -Xcomp -XX:+UseCompactObjectHeaders -Djdk.lang.processReaperUseDefaultStackSize=true test/hotspot/jtreg/serviceability/sa/TestJmapCore.java 
export test=test/hotspot/jtreg/serviceability/sa/TestJmapCore.java
function runJtreg() { jtreg -Xcomp -XX:+UseCompactObjectHeaders -Djdk.lang.processReaperUseDefaultStackSize=true -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ; else rm -rf $dir/index-$1 $dir/$1.log ; fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 80 | xargs -i -n 1 -P `nproc` bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
```

```
Threads class SMR info:
_java_thread_list=0x0000ffff440024d0, length=14, elements={
0x0000ffffb0033800, 0x0000ffffb0471800, 0x0000ffffb047d000, 0x0000ffffb04ac800,
0x0000ffffb04b7000, 0x0000ffffb04ba000, 0x0000ffffb04bc800, 0x0000ffffb04bf000,
0x0000ffffb05a5800, 0x0000ffffb0601800, 0x0000ffff1c13a000, 0x0000ffff1c0b7800,
0x0000ffff1c06c800, 0x0000ffff44001000
}
_java_thread_list_alloc_cnt=31, _java_thread_list_free_cnt=30, _java_thread_list_max=17, _nested_thread_list_max=0
_tlh_cnt=399, _tlh_times=0, avg_tlh_time=0.00, _tlh_time_max=0
_deleted_thread_cnt=8, _deleted_thread_times=0, avg_deleted_thread_time=0.00, _deleted_thread_time_max=0
_delete_lock_wait_cnt=0, _delete_lock_wait_max=0
_to_delete_list_cnt=0, _to_delete_list_max=1

"main" #1 prio=5 os_prio=0 cpu=180.31ms elapsed=2400.55s tid=0x0000ffffb0033800 nid=0x19705a in Object.wait()  [0x0000ffffb691e000]
   java.lang.Thread.State: WAITING (on object monitor)
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb0033800  [0x19705a] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
	at java.lang.Object.wait(java.base@11.0.21.17/Native Method)
	- waiting on <0x000000046b7e9b48> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.21.17/Thread.java:1450)
	- waiting to re-lock in wait() <0x000000046b7e9b48> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.21.17/Thread.java:1525)
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.21ms elapsed=2400.50s tid=0x0000ffffb0471800 nid=0x197064 waiting on condition  [0x0000ffff5fd7c000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb0471800  [0x197064] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.21.17/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.21.17/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.21.17/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.55ms elapsed=2400.50s tid=0x0000ffffb047d000 nid=0x197065 in Object.wait()  [0x0000ffff5fb7c000]
   java.lang.Thread.State: WAITING (on object monitor)
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb047d000  [0x197065] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
	at java.lang.Object.wait(java.base@11.0.21.17/Native Method)
	- waiting on <0x000000046b40c430> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.21.17/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x000000046b40c430> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.21.17/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.21.17/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.49ms elapsed=2400.48s tid=0x0000ffffb04ac800 nid=0x197066 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb04ac800  [0x197066] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.10ms elapsed=2400.48s tid=0x0000ffffb04b7000 nid=0x197067 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb04b7000  [0x197067] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=91.48ms elapsed=2400.48s tid=0x0000ffffb04ba000 nid=0x197068 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb04ba000  [0x197068] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
   No compile task

"C1 CompilerThread0" #16 daemon prio=9 os_prio=0 cpu=123.61ms elapsed=2400.48s tid=0x0000ffffb04bc800 nid=0x197069 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb04bc800  [0x197069] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
   No compile task

"Sweeper thread" #21 daemon prio=9 os_prio=0 cpu=0.07ms elapsed=2400.48s tid=0x0000ffffb04bf000 nid=0x19706a runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb04bf000  [0x19706a] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked

"Common-Cleaner" #22 daemon prio=8 os_prio=0 cpu=2.72ms elapsed=2400.42s tid=0x0000ffffb05a5800 nid=0x19706f in Object.wait()  [0x0000ffff5e77b000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb05a5800  [0x19706f] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
	at java.lang.Object.wait(java.base@11.0.21.17/Native Method)
	- waiting on <0x000000046b49d528> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.21.17/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x000000046b49d528> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.21.17/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.21.17/Thread.java:955)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.21.17/InnocuousThread.java:161)

"MainThread" #24 prio=5 os_prio=0 cpu=243.81ms elapsed=2400.37s tid=0x0000ffffb0601800 nid=0x197070 in Object.wait()  [0x0000ffff5e504000]
   java.lang.Thread.State: WAITING (on object monitor)
   JavaThread state: _thread_blocked
Thread: 0x0000ffffb0601800  [0x197070] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_blocked
	at java.lang.Object.wait(java.base@11.0.21.17/Native Method)
	- waiting on <0x000000046a812ea0> (a java.lang.ProcessImpl)
	at java.lang.Object.wait(java.base@11.0.21.17/Object.java:328)
	at java.lang.ProcessImpl.waitFor(java.base@11.0.21.17/ProcessImpl.java:495)
	- waiting to re-lock in wait() <0x000000046a812ea0> (a java.lang.ProcessImpl)
	at TestJmapCore.test(TestJmapCore.java:133)
	at TestJmapCore.main(TestJmapCore.java:73)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.21.17/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.21.17/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.21.17/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.21.17/Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(java.base@11.0.21.17/Thread.java:955)

"process reaper (pid 1667475)" #25 daemon prio=10 os_prio=0 cpu=7.93ms elapsed=2400.21s tid=0x0000ffff1c13a000 nid=0x197073 runnable  [0x0000ffff5e105000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_in_native
Thread: 0x0000ffff1c13a000  [0x197073] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_in_native
	at java.lang.ProcessHandleImpl.waitForProcessExit0(java.base@11.0.21.17/Native Method)
	at java.lang.ProcessHandleImpl$1.run(java.base@11.0.21.17/ProcessHandleImpl.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.21.17/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.21.17/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.21.17/Thread.java:955)

"Thread-5" #30 daemon prio=5 os_prio=0 cpu=0.52ms elapsed=2393.97s tid=0x0000ffff1c0b7800 nid=0x197196 runnable  [0x0000ffff5ed7b000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_in_native
Thread: 0x0000ffff1c0b7800  [0x197196] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_in_native
	at java.io.FileInputStream.readBytes0(java.base@11.0.21.17/Native Method)
	at java.io.FileInputStream.readBytes(java.base@11.0.21.17/FileInputStream.java:256)
	at java.io.FileInputStream.read(java.base@11.0.21.17/FileInputStream.java:294)
	at java.io.BufferedInputStream.read1(java.base@11.0.21.17/BufferedInputStream.java:290)
	at java.io.BufferedInputStream.read(java.base@11.0.21.17/BufferedInputStream.java:351)
	- locked <0x000000046a815048> (a java.lang.ProcessImpl$ProcessPipeInputStream)
	at java.io.BufferedInputStream.fill(java.base@11.0.21.17/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read1(java.base@11.0.21.17/BufferedInputStream.java:292)
	at java.io.BufferedInputStream.read(java.base@11.0.21.17/BufferedInputStream.java:351)
	- locked <0x000000046a8f6508> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(java.base@11.0.21.17/FilterInputStream.java:107)
	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.21.17/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.21.17/FutureTask.java:264)
	at java.lang.Thread.run(java.base@11.0.21.17/Thread.java:955)

"Thread-6" #31 daemon prio=5 os_prio=0 cpu=0.33ms elapsed=2393.97s tid=0x0000ffff1c06c800 nid=0x197197 runnable  [0x0000ffff5df04000]
   java.lang.Thread.State: RUNNABLE
   JavaThread state: _thread_in_native
Thread: 0x0000ffff1c06c800  [0x197197] State: _at_safepoint _has_called_back 0 _at_poll_safepoint 0
   JavaThread state: _thread_in_native
	at java.io.FileInputStream.readBytes0(java.base@11.0.21.17/Native Method)
	at java.io.FileInputStream.readBytes(java.base@11.0.21.17/FileInputStream.java:256)
	at java.io.FileInputStream.read(java.base@11.0.21.17/FileInputStream.java:294)
	at java.io.BufferedInputStream.read1(java.base@11.0.21.17/BufferedInputStream.java:290)
	at java.io.BufferedInputStream.read(java.base@11.0.21.17/BufferedInputStream.java:351)
	- locked <0x000000046a8170f0> (a java.lang.ProcessImpl$ProcessPipeInputStream)
	at java.io.BufferedInputStream.fill(java.base@11.0.21.17/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read1(java.base@11.0.21.17/BufferedInputStream.java:292)
	at java.io.BufferedInputStream.read(java.base@11.0.21.17/BufferedInputStream.java:351)
	- locked <0x000000046a9ec158> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(java.base@11.0.21.17/FilterInputStream.java:107)
	at jdk.test.lib.process.StreamPumper.run(StreamPumper.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.21.17/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.21.17/FutureTask.java:264)
	at java.lang.Thread.run(java.base@11.0.21.17/Thread.java:955)
```

```
> uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; java -version ; java -Xinternalversion
Linux ano86-x64.sqa.eu95 4.19.91-27.5.an8.x86_64 #1 SMP Sat Jul 22 10:21:33 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Anolis OS"
VERSION="8.8"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.8"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.8"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:          188Gi       6.3Gi       155Gi       3.3Gi        26Gi       176Gi
Swap:         2.0Gi       1.4Gi       588Mi
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping:            4
CPU MHz:             1626.024
CPU max MHz:         3100.0000
CPU min MHz:         1000.0000
BogoMIPS:            5000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities
openjdk version "11.0.21.17" 2023-12-15
OpenJDK Runtime Environment (Alibaba Dragonwell) (fastdebug build 11.0.21.17+0)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (fastdebug build 11.0.21.17+0, mixed mode)
OpenJDK 64-Bit Server VM (fastdebug 11.0.21.17+0) for linux-amd64 JRE (11.0.21.17+0), built on Dec 15 2023 03:27:13 by "" with gcc 9.3.1 20200408 (Red Hat 9.3.1-2)
```

**Comment by sendaoYan** [comment]
未复现，先关闭

![image](https://github.com/dragonwell-project/dragonwell11/assets/24123821/e9d5bed9-91fe-456a-915e-e5e4038dc76d)
