### ISSUE TITLE
[riscv64]serviceability/sa相关的用例报错OS/CPU combination linux/riscv64 not yet supported

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#768]
相关的用例：

```
serviceability/sa/CDSJMapClstats.java
serviceability/sa/ClhsdbCDSCore.java
serviceability/sa/ClhsdbCDSJstackPrintAll.java
serviceability/sa/ClhsdbFindPC.java
serviceability/sa/ClhsdbInspect.java
serviceability/sa/ClhsdbJdis.java
serviceability/sa/ClhsdbJhisto.java
serviceability/sa/ClhsdbJstack.java
serviceability/sa/ClhsdbJstackXcompStress.java
serviceability/sa/ClhsdbPrintAs.java
serviceability/sa/ClhsdbPstack.java
serviceability/sa/ClhsdbSource.java
serviceability/sa/ClhsdbThread.java
serviceability/sa/ClhsdbWhere.java
serviceability/sa/DeadlockDetectionTest.java
serviceability/sa/JhsdbThreadInfoTest.java
serviceability/sa/TestClhsdbJstackLock.java
serviceability/sa/TestHeapDumpForInvokeDynamic.java
serviceability/sa/TestJhsdbJstackLock.java
serviceability/sa/TestJhsdbJstackMixed.java
serviceability/sa/TestJmapCore.java
serviceability/sa/TestJmapCoreMetaspace.java
serviceability/sa/jmap-hprof/JMapHProfLargeHeapTest.java
serviceability/sa/sadebugd/DebugdConnectTest.java
```

```
Command line: ['/tmp/tone/run/jtreg/binary-download/dragonwell-11.0.21.18+9-GA/bin/java' '-Xcomp' '-cp' '/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/0/serviceability/sa/ClhsdbFindPC.d:/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/0/test/lib' 'LingeredAppWithTrivialMain' '4ef7e820-1ecc-4118-9620-0cbf3374b7d6.lck' ]
Attaching to process 347072, please wait...
Warning: Nashorn engine is planned to be removed from a future JDK release
javax.script.ScriptException: TypeError: sapkg.runtime.VM.getVM is not a function in sa.js at line number 54
javax.script.ScriptException: TypeError: sapkg.runtime.VM.getVM is not a function in sa.js at line number 54
Exception in thread "main" java.lang.ExceptionInInitializerError
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.VM.getThreads(VM.java:728)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:54)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
	at jdk.hotspot.agent/sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor$24.doit(CommandProcessor.java:1066)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.executeCommand(CommandProcessor.java:1974)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.executeCommand(CommandProcessor.java:1944)
	at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.run(CommandProcessor.java:1824)
	at jdk.hotspot.agent/sun.jvm.hotspot.CLHSDB.run(CLHSDB.java:99)
	at jdk.hotspot.agent/sun.jvm.hotspot.CLHSDB.main(CLHSDB.java:40)
	at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.runCLHSDB(SALauncher.java:224)
	at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.main(SALauncher.java:522)
Caused by: java.lang.RuntimeException: OS/CPU combination linux/riscv64 not yet supported
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.Threads.initialize(Threads.java:109)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.Threads$1.update(Threads.java:58)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.VM.registerVMInitializedObserver(VM.java:515)
	at jdk.hotspot.agent/sun.jvm.hotspot.runtime.Threads.<clinit>(Threads.java:56)
	... 12 more
 stdout: [Warning! JS Engine can't start, some commands will not be available.
hsdb> Deadlock Detection:
```

[jtreg.stdout.log.zip](https://github.com/dragonwell-project/dragonwell11/files/13840125/jtreg.stdout.log.zip)

**Comment by kuaiwei** [comment]
It's reproduced of https://github.com/dragonwell-project/dragonwell11/issues/770, close
