### ISSUE TITLE
[upstream][TESTBUG]tools/jpackage/linux/LinuxResourceTest.java fail

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#781]
job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/269543?tab=1

JBS BUG: https://bugs.openjdk.org/browse/JDK-8316563

```
18:18:13.347] TRACE: Verify unpacked: [/tmp/tone/run/jtreg/jdk-repo/build/linux-aarch64-server-release/images/jdk/bin/jpackage --input ./testHardcodedProperties/input --dest ./testHardcodedProperties/output --name HardcodedPropertiesLinuxResourceTest --type rpm --main-jar hello.jar --main-class Hello --resource-dir ./testHardcodedProperties/resources --runtime-image ./testHardcodedProperties/fake_runtime jpt-unpacked-folder ./testHardcodedProperties/unpacked-rpm](19)
[18:18:13.359] ERROR: Expected [1]. Actual [2]: Check the package has 1 top installation directories
[18:18:13.360] [  FAILED  ] LinuxResourceTest.testHardcodedProperties; checks=16
[18:18:13.361] [==========] 1 tests ran
[18:18:13.361] [  PASSED  ] 0 tests
[18:18:13.364] [  FAILED  ] 1 test, listed below
[18:18:13.365] [  FAILED  ] LinuxResourceTest.testHardcodedProperties; workDir=[./testHardcodedProperties]
[18:18:13.365] 1 FAILED TEST
STDERR:
java.lang.AssertionError: Expected [1]. Actual [2]: Check the package has 1 top installation directories
	at jdk.jpackage.test.TKit.error(TKit.java:273)
	at jdk.jpackage.test.TKit.assertEquals(TKit.java:576)
	at jdk.jpackage.test.PackageTest$Handler.verifyRootCountInUnpackedPackage(PackageTest.java:705)
	at jdk.jpackage.test.PackageTest$Handler.lambda$verifyPackageInstalled$3(PackageTest.java:635)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at jdk.jpackage.test.PackageTest$Handler.verifyPackageInstalled(PackageTest.java:633)
	at jdk.jpackage.test.PackageTest$Handler.accept(PackageTest.java:592)
	at jdk.jpackage.test.PackageTest$2.accept(PackageTest.java:504)
	at jdk.jpackage.test.PackageTest$2.accept(PackageTest.java:411)
	at jdk.jpackage.test.Functional$ThrowingConsumer.lambda$toConsumer$0(Functional.java:41)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at jdk.jpackage.test.PackageTest.lambda$runActions$24(PackageTest.java:381)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at jdk.jpackage.test.PackageTest.lambda$runActions$25(PackageTest.java:380)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at jdk.jpackage.test.PackageTest.runActions(PackageTest.java:379)
	at jdk.jpackage.test.RunnablePackageTest.run(RunnablePackageTest.java:58)
	at LinuxResourceTest.testHardcodedProperties(LinuxResourceTest.java:135)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at jdk.jpackage.test.MethodCall.accept(MethodCall.java:145)
	at jdk.jpackage.test.TestInstance.run(TestInstance.java:230)
	at jdk.jpackage.test.TKit.lambda$ignoreExceptions$5(TKit.java:141)
	at jdk.jpackage.test.TKit.lambda$runTests$3(TKit.java:126)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at jdk.jpackage.test.TKit.lambda$runTests$4(TKit.java:123)
	at jdk.jpackage.test.Functional$ThrowingRunnable.lambda$toRunnable$0(Functional.java:105)
	at jdk.jpackage.test.TKit.withExtraLogStream(TKit.java:109)
	at jdk.jpackage.test.TKit.runTests(TKit.java:122)
	at jdk.jpackage.test.Main.runTests(Main.java:79)
	at jdk.jpackage.test.Main.lambda$main$2(Main.java:75)
	at jdk.jpackage.test.Functional$ThrowingRunnable.lambda$toRunnable$0(Functional.java:105)
	at jdk.jpackage.test.TKit.withExtraLogStream(TKit.java:109)
	at jdk.jpackage.test.Main.main(Main.java:75)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.RuntimeException: 1 FAILED TEST
	at jdk.jpackage.test.Main.reportSummary(Main.java:130)
	at jdk.jpackage.test.Main.runTests(Main.java:90)
	at jdk.jpackage.test.Main.lambda$main$2(Main.java:75)
	at jdk.jpackage.test.Functional$ThrowingRunnable.lambda$toRunnable$0(Functional.java:105)
	at jdk.jpackage.test.TKit.withExtraLogStream(TKit.java:109)
	at jdk.jpackage.test.Main.main(Main.java:75)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk17u-dev/pull/2138

**Comment by sendaoYan** [comment]
https://github.com/dragonwell-project/dragonwell17/issues/192
