### ISSUE TITLE
[network]security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#actalisauthenticationrootca intermittently timeout

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#782]
job：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/270107?tab=1

```
"MainThread" #25 prio=5 os_prio=0 cpu=340.38ms elapsed=480.13s tid=0x00007f9178252eb0 nid=0x3fb3b0 runnable  [0x00007f912d1ef000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.SocketDispatcher.read0(java.base@17.0.11/Native Method)
	at sun.nio.ch.SocketDispatcher.read(java.base@17.0.11/SocketDispatcher.java:47)
	at sun.nio.ch.NioSocketImpl.tryRead(java.base@17.0.11/NioSocketImpl.java:266)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.11/NioSocketImpl.java:317)
	at sun.nio.ch.NioSocketImpl.read(java.base@17.0.11/NioSocketImpl.java:355)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.11/NioSocketImpl.java:808)
	at java.net.Socket$SocketInputStream.read(java.base@17.0.11/Socket.java:966)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@17.0.11/SSLSocketInputRecord.java:484)
	at sun.security.ssl.SSLSocketInputRecord.readFully(java.base@17.0.11/SSLSocketInputRecord.java:467)
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(java.base@17.0.11/SSLSocketInputRecord.java:243)
	at sun.security.ssl.SSLSocketInputRecord.decode(java.base@17.0.11/SSLSocketInputRecord.java:181)
	at sun.security.ssl.SSLTransport.decode(java.base@17.0.11/SSLTransport.java:111)
	at sun.security.ssl.SSLSocketImpl.decode(java.base@17.0.11/SSLSocketImpl.java:1510)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(java.base@17.0.11/SSLSocketImpl.java:1425)
	at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@17.0.11/SSLSocketImpl.java:455)
	at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@17.0.11/SSLSocketImpl.java:426)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(java.base@17.0.11/HttpsClient.java:589)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(java.base@17.0.11/AbstractDelegateHttpsURLConnection.java:187)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(java.base@17.0.11/HttpsURLConnectionImpl.java:142)
	at ValidatePathWithURL.validateDomainCertChain(ValidatePathWithURL.java:142)
	at ValidatePathWithURL.validateDomain(ValidatePathWithURL.java:128)
	at CAInterop.validate(CAInterop.java:692)
	at CAInterop.main(CAInterop.java:630)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.11/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.11/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.11/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.11/Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.lang.Thread.run(java.base@17.0.11/Thread.java:840)
```

[jtreg.stdout.log](https://github.com/dragonwell-project/dragonwell11/files/13976735/jtreg.stdout.log)

**Comment by sendaoYan** [comment]
https://github.com/dragonwell-project/dragonwell17/issues/193
