### ISSUE TITLE
[upstream]java/math/BigInteger/largeMemory/SymmetricRangeTests.java fail with -XX:+ UseCompressedOops java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#788]
test command:
```bash
j -XX:-UseCompressedOops test/jdk/java/math/BigInteger/largeMemory/SymmetricRangeTests.java
```

result:
```
STDOUT:
Testing overflow in BigInteger.makePositive
STDERR:
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at SymmetricRangeTests.testOverflowInMakePositive(SymmetricRangeTests.java:88)
        at SymmetricRangeTests.main(SymmetricRangeTests.java:624)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

jdk17/jdk21/jdk23均没有问题

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/15607151
