### ISSUE TITLE
[upstream]sun/security/ec/TestEC.java fail

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#808]
job: 
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/299132
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/299133

```
java.lang.ExceptionInInitializerError
	at PKCS11Test.fetchNssLib(PKCS11Test.java:932)
	at PKCS11Test.getPreferableNssLibPaths(PKCS11Test.java:787)
	at PKCS11Test.getNssLibPaths(PKCS11Test.java:772)
	at PKCS11Test.getNSSLibPath(PKCS11Test.java:387)
	at PKCS11Test.getNSSLibPath(PKCS11Test.java:382)
	at PKCS11Test.getNSSInfo(PKCS11Test.java:509)
	at PKCS11Test.getNSSInfo(PKCS11Test.java:486)
	at PKCS11Test.getNSSECC(PKCS11Test.java:468)
	at TestECDSA.main(TestECDSA.java:159)
	at TestEC.main0(TestEC.java:103)
	at TestEC.main(TestEC.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "java.vm.info" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
	at java.base/java.lang.System.getProperty(System.java:830)
	at jdk.test.lib.Platform.lambda$privilegedGetProperty$0(Platform.java:56)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jdk.test.lib.Platform.privilegedGetProperty(Platform.java:55)
	at jdk.test.lib.Platform.<clinit>(Platform.java:41)
	... 17 more
```

单跑没有复现
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/300978

**Comment by sendaoYan** [comment]
https://git.openjdk.java.net/jdk/pull/366
