### ISSUE TITLE
[dragonwell11][riscv64][extended]serviceability/sa/ClhsdbInspect.java等17个用例报错OS/CPU combination linux/riscv64 not yet supported

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#816]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/306034?tab=1<br>
【环境准备】

```
登录环境：
30.220.116.74

BINARY_URL=oss://dragonwell/11.0.23.20.9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_11.0.23.20.9_riscv64_linux.tar.gz
TEST_IMAGE=oss://dragonwell/11.0.23.20.9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_11.0.23.20.9_riscv64_linux-testimage.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg-6.1.1.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell11.git
JDK_BRANCH=dragonwell_extended-11.0.23.20.9
alias oss="/tmp/tone/tone-matrix-compiler/common/ossutil.bin_riscv64 -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev  -b /tmp/tone/run/jtreg/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir binary-download;tar -xf ${BINARY_URL##*/} -C binary-download
oss $TEST_IMAGE-l ${TEST_IMAGE##*/}
mkdir test-images;tar -xf ${BINARY_URL##*/} -C test-images

cd binary-download/dragonwell-11.0.22.19+7-ga/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO ajdk-repo

执行以下命令：
test="]serviceability/sa/ClhsdbInspect.java"
args="-Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -Xmixed -ea -esa"
native=-nativepath:test-images/dragonwell-11.0.22.19+7-ga-test-image/hotspot/jtreg/native
jtreg  -nr -v:fail,error -w tmp  $args $native  $test
```

涉及17个用例：<br>
serviceability/sa/ClhsdbFindPC.java<br>
serviceability/sa/ClhsdbInspect.java<br>
serviceability/sa/ClhsdbJdis.java<br>
serviceability/sa/ClhsdbJstack.java<br>
serviceability/sa/ClhsdbJstackXcompStress.java<br>
serviceability/sa/ClhsdbPrintAs.java<br>
serviceability/sa/ClhsdbPstack.java<br>
sun/tools/jhsdb/HeapDumpTest.java<br>
serviceability/sa/ClhsdbSource.java<br>
serviceability/sa/ClhsdbThread.java<br>
serviceability/sa/JhsdbThreadInfoTest.java<br>
serviceability/sa/TestClhsdbJstackLock.java<br>
serviceability/sa/TestJhsdbJstackLock.java<br>
serviceability/sa/TestJhsdbJstackMixed.java<br>
serviceability/sa/sadebugd/DebugdConnectTest.java<br>
serviceability/sa/ClhsdbCDSJstackPrintAll.java<br>
serviceability/sa/ClhsdbWhere.java<br>

【对比测试】<br>
dragonwell release 同样问题 
oss://dragonwell/11.0.22.19.7/Alibaba_Dragonwell_Extended_11.0.22.19.7_riscv64_linux.tar.gz

```
[root@fedora-riscv jtreg]#  bin-release/dragonwell-11.0.22.19+7-ga/bin/java -version
openjdk version "11.0.22.19" 2024-01-16
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.22.19+7-ga (build 11.0.22.19+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.22.19+7-ga (build 11.0.22.19+7, mixed mode)
[root@fedora-riscv jtreg]#  bin-release/dragonwell-11.0.22.19+7-ga/bin/java -Xinternalversion
OpenJDK 64-Bit Server VM (11.0.22.19+7) for linux-riscv64 JRE (11.0.22.19+7), built on Mar  5 2024 04:12:27 by "" with gcc 9.2.0
```
dragonwell release部分用例报错现象不同

```
STDERR:
Command line: ['/tmp/tone/run/jtreg/bin-release/dragonwell-11.0.22.19+7-ga/bin/java' '-Djdk.lang.processReaperUseDefaultStackSize=true' '-Dtest.wisp.socketAddress=www.alibabacloud.com' '-Xmixed' '-ea' '-esa' '-cp' '/tmp/tone/run/jtreg/tmp/classes/serviceability/sa/ClhsdbJdis.d:/tmp/tone/run/jtreg/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '00b7438d-42ee-43cd-bb91-e61985f9aedb.lck' ]
Attaching to process 201658, please wait...
Warning: Nashorn engine is planned to be removed from a future JDK release
javax.script.ScriptException: TypeError: sapkg.runtime.VM.getVM is not a function in sa.js at line number 54
javax.script.ScriptException: TypeError: sapkg.runtime.VM.getVM is not a function in sa.js at line number 54
Exception in thread "main" java.lang.ExceptionInInitializerError
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.VM.getThreads(VM.java:728)
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:54)
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
        at jdk.hotspot.agent/sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
        at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor$24.doit(CommandProcessor.java:1066)
        at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.executeCommand(CommandProcessor.java:1974)
        at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.executeCommand(CommandProcessor.java:1944)
        at jdk.hotspot.agent/sun.jvm.hotspot.CommandProcessor.run(CommandProcessor.java:1824)
        at jdk.hotspot.agent/sun.jvm.hotspot.CLHSDB.run(CLHSDB.java:99)
        at jdk.hotspot.agent/sun.jvm.hotspot.CLHSDB.main(CLHSDB.java:40)
        at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.runCLHSDB(SALauncher.java:224)
        at jdk.hotspot.agent/sun.jvm.hotspot.SALauncher.main(SALauncher.java:522)
Caused by: java.lang.RuntimeException: OS/CPU combination linux/riscv64 not yet supported
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.Threads.initialize(Threads.java:109)
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.Threads$1.update(Threads.java:58)
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.VM.registerVMInitializedObserver(VM.java:515)
        at jdk.hotspot.agent/sun.jvm.hotspot.runtime.Threads.<clinit>(Threads.java:56)
        ... 12 more
 stdout: [Warning! JS Engine can't start, some commands will not be available.
hsdb> Deadlock Detection:

];
 stderr: []
 exitValue = 1

 LingeredApp stdout: [];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
java.lang.RuntimeException: Test ERROR java.lang.RuntimeException: Expected to get exit value of [0]

        at ClhsdbJdis.main(ClhsdbJdis.java:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:955)
Caused by: java.lang.RuntimeException: Expected to get exit value of [0]

        at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:431)
        at ClhsdbLauncher.runCmd(ClhsdbLauncher.java:127)
        at ClhsdbLauncher.run(ClhsdbLauncher.java:177)
        at ClhsdbJdis.main(ClhsdbJdis.java:54)
        ... 6 more

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test ERROR java.lang.RuntimeException: Expected to get exit value of [0]
```

【用例日志】<br>
完整日志：[1.log](https://code.alibaba-inc.com/api/v4/projects/2830220/attachment/getViewUrl?fileIdentifier=alibaba/61036/17149883717541.log)

```
Warning: Nashorn engine is planned to be removed from a future JDK release
javax.script.ScriptException: TypeError: sapkg.runtime.VM.getVM is not a function in sa.js at line number 54
javax.script.ScriptException: TypeError: sapkg.runtime.VM.getVM is not a function in sa.js at line number 54
 stdout: [ Error: java.lang.NumberFormatException: null
];
 stderr: [ Error: java.lang.NumberFormatException: null
]
 exitValue = -1

 LingeredApp stdout: [];
 LingeredApp stderr: []
 LingeredApp exitValue = 0
java.lang.RuntimeException: Test ERROR java.lang.RuntimeException: 'instance of Oop for java/lang/Class' missing from stdout/stderr 

	at ClhsdbInspect.main(ClhsdbInspect.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)
Caused by: java.lang.RuntimeException: 'instance of Oop for java/lang/Class' missing from stdout/stderr 

	at jdk.test.lib.process.OutputAnalyzer.shouldMatch(OutputAnalyzer.java:282)
	at ClhsdbLauncher.runCmd(ClhsdbLauncher.java:140)
	at ClhsdbLauncher.run(ClhsdbLauncher.java:177)
	at ClhsdbInspect.main(ClhsdbInspect.java:95)
	... 6 more

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test ERROR java.lang.RuntimeException: 'instance of Oop for java/lang/Class' missing from stdout/stderr 

JavaTest Message: shutting down test
```

【版本信息】

```
[root@fedora-riscv bin]# uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; ./java -version ; ./java -Xinternalversion
Linux fedora-riscv 6.1.22 #2 SMP Thu May  4 19:24:40 CST 2023 riscv64 GNU/Linux
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
               total        used        free      shared  buff/cache   available
Mem:            62Gi       990Mi        54Gi       6.1Gi       7.3Gi        55Gi
Swap:          8.0Gi          0B       8.0Gi
Architecture:        riscv64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
NUMA node(s):        4
NUMA node0 CPU(s):   0-7,16-23
NUMA node1 CPU(s):   8-15,24-31
NUMA node2 CPU(s):   32-39,48-55
NUMA node3 CPU(s):   40-47,56-63
openjdk version "11.0.23.19" 2024-04-16
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.22.19+7-ga (build 11.0.23.19+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.22.19+7-ga (build 11.0.23.19+7, mixed mode)
OpenJDK 64-Bit Server VM (11.0.23.19+7) for linux-riscv64 JRE (11.0.23.19+7), built on Apr 26 2024 03:22:06 by "" with gcc 9.2.0
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/16566995
