### ISSUE TITLE
[riscv64]java/net/MulticastSocket/Test.java report 'No such device'

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#831]
```
2 test(s) executed. 1 test(s) failed.
STDERR:
java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:235)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
	at Test.doTest(Test.java:70)
	at Test.allTests(Test.java:144)
	at Test.main(Test.java:164)
```

[jtreg.log](https://github.com/user-attachments/files/15507332/jtreg.log)

```
# uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25 ; java -version ; java -Xinternalversion ; git remote -v ; git log -n 1 | head -n 1
Linux fedora-riscv 6.1.22 #2 SMP Thu May  4 19:24:40 CST 2023 riscv64 GNU/Linux
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
               total        used        free      shared  buff/cache   available
Mem:            62Gi       1.3Gi        50Gi        16Mi        10Gi        60Gi
Swap:          8.0Gi       4.0Mi       8.0Gi
Architecture:        riscv64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
NUMA node(s):        4
NUMA node0 CPU(s):   0-7,16-23
NUMA node1 CPU(s):   8-15,24-31
NUMA node2 CPU(s):   32-39,48-55
NUMA node3 CPU(s):   40-47,56-63
openjdk version "11.0.24" 2024-07-16
OpenJDK Runtime Environment (build 11.0.24+0)
OpenJDK 64-Bit Server VM (build 11.0.24+0, mixed mode)
OpenJDK 64-Bit Server VM (11.0.24+0) for linux-riscv64 JRE (11.0.24+0), built on May 30 2024 12:17:02 by "yansendao" with gcc 13.2.1 20230728 (Red Hat 13.2.1-1)
origin  git@github.com:sendaoYan/riscv-port-jdk11u-ysd.git (fetch)
origin  git@github.com:sendaoYan/riscv-port-jdk11u-ysd.git (push)
commit 5fed2d905d6171ce66a81ecbb81d190929a1a333
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/16910478
