### ISSUE TITLE
[anolis]jdk/javadoc/doclet/testIOException/TestIOException.java fails java.lang.Error: index is writable

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#839]
代码仓：https://gitee.com/src-anolis-sig/java-11-alibaba-dragonwell/tree/a8/

测试命令：
```shell
yum-builddep -y xxx.spec
mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,BUILDROOT}
\cp -rf jtreg-6.1.1.zip java-11-alibaba-dragonwell.spec dragonwell-extended-11.0.21.18_jdk-11.0.21-ga.tar.gz tapsets-icedtea-6.0.0pre00-c848b93a8598.tar.xz rpmbuild/SOURCES/
time rpmbuild -ba --define "_topdir $PWD/rpmbuild"  *.spec 2>&1 | tee build.log
```
测试日志：
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at JavadocTester.runTests(JavadocTester.java:291)
	at JavadocTester.runTests(JavadocTester.java:275)
	at TestIOException.main(TestIOException.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:955)
Caused by: java.lang.Error: index is writable
	at TestIOException.testReadOnlyFile(TestIOException.java:80)
	... 13 more
```

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk/pull/19731
