### ISSUE TITLE
[11.0.25.22.9][aarch64]jdk/crac/下23个用例失败cannot find CRIU to use

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#885]
任务链接：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/398084?tab=1

【环境准备】
```
BINARY_URL=oss://dragonwell/11.0.25.22.9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_11.0.25.22.9_aarch64_linux.tar.gz
TEST_IMAGE=oss://dragonwell/11.0.25.22.9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_11.0.25.22.9_aarch64_linux-testimage.tar.gz
JDK_REPO=git@github.com:dragonwell-project/dragonwell11.git
JDK_BRANCH=dragonwell_extended-11.0.25.22.9

jtreg=oss://compiler-ci-bucket/jdk/tools/jtreg-7.4.1.zip

#下载解压jtreg，cd jtreg并配置
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
#下载解压jdk，cd <目录>并配置
export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME
#下载jdk-repo
git clone https://${JDK_REPO} --depth 1 -b $JDK_BRANCH jdk-repo

#执行测试
jtreg -w tmp -nr -v:fail,error  jdk/crac/AppendOnlyFileTest.java



```   

【测试分析】

```   
涉及case 共计24个：
jdk/crac/AppendAppClassLoaderTest.java
jdk/crac/AppendOnlyFileTest.java
jdk/crac/LeaveRunning.java
jdk/crac/PseudoPersistentFileTest.java
jdk/crac/RestoreEnvironmentTest.java
jdk/crac/RestorePipeFdTest.java
jdk/crac/SecureRandom/InterlockTest.java
jdk/crac/SecureRandom/ReseedTest.java
jdk/crac/Selector/Test970/Test.java
jdk/crac/Selector/interruptedSelection/Test.java
jdk/crac/Selector/keyAfterRestore/Test.java
jdk/crac/Selector/multipleSelect/Test.java
jdk/crac/Selector/multipleSelectNow/Test.java
jdk/crac/Selector/multipleSelectSingleClose/Test.java
jdk/crac/Selector/selectAfterWakeup/Test.java
jdk/crac/Selector/selectAndWakeupAfterRestore/Test.java
jdk/crac/Selector/wakeupAfterRestore/Test.java
jdk/crac/Selector/wakeupByClose/Test.java
jdk/crac/Selector/wakeupByTimeoutAfterRestore/Test.java
jdk/crac/fileDescriptors/CheckpointWithOpenFdsTest.java
jdk/crac/fileDescriptors/IgnoredFileDescriptorsTest.java
jdk/crac/java/lang/Thread/JoinSleepWaitOnCRPauseTest.java
jdk/crac/java/net/InetAddress/ResolveTest.java
jdk/crac/stdoutInDocker/TestStdoutInDocker.sh


arm上fail。x64上pass

release版本不支持

```

【版本信息】     

#jdk信息   
```
openjdk version "11.0.25.21" 2024-10-15
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.24.21+8-ga (build 11.0.25.21+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.24.21+8-ga (build 11.0.25.21+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.25.21+8) for linux-aarch64 JRE (11.0.25.21+8), built on Nov  4 2024 09:22:03 by "" with gcc 7.5.0

 
```    

#测试机信息jdk环境信息     
```
[root@CompilerTest-x64-5 ~]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25; dmidecode -t chassis
Linux CompilerTest-x64-5 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       711Mi       116Gi       2.0Mi       5.9Gi       121Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
BIOS Model name:     pc-i440fx-2.1
Stepping:            6
CPU MHz:             3502.594
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0300, DMI type 3, 21 bytes
Chassis Information
        Manufacturer: Alibaba Cloud
        Type: Other
        Lock: Not Present
        Version: pc-i440fx-2.1
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Boot-up State: Safe
        Power Supply State: Safe
        Thermal State: Safe
        Security Status: Unknown
        OEM Information: 0x00000000
        Height: Unspecified
        Number Of Power Cords: Unspecified
        Contained Elements: 0




```

【用例日志】
```
STDERR:
Note: /tmp/tone/run/jtreg/jdk-repo/test/lib/jdk/test/lib/crac/CracTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

ACTION: driver -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Checkpointed process was not killed as expected.: expected 137 to equal 1
REASON: User specified action: run driver/timeout=30 jdk.test.lib.crac.CracTest true true false 
TIME:   1.477 seconds
messages:
command: driver jdk.test.lib.crac.CracTest true true false
reason: User specified action: run driver/timeout=30 jdk.test.lib.crac.CracTest true true false 
started: Tue Nov 05 18:55:34 CST 2024
Mode: othervm
finished: Tue Nov 05 18:55:36 CST 2024
elapsed time (seconds): 1.477
configuration:
STDOUT:
>> interrupt before checkpoint
CR: Checkpoint ...
STDERR:
Starting process to be checkpointed:
/tmp/tone/run/jtreg/binary-download/dragonwell-11.0.24.21+8-ga/bin/java -ea -cp /tmp/tone/run/jtreg/jt-work/crac/classes/15/jdk/crac/Selector/interruptedSelection/Test.d:/tmp/tone/run/jtreg/jt-work/crac/classes/15/test/lib -XX:CRaCCheckpointTo=cr jdk.test.lib.crac.CracTest __run_test__ Test true true false
cannot find CRIU to use
Exception in thread "main" jdk.crac.CheckpointException
	at java.base/jdk.crac.Core.checkpointRestore1(Core.java:147)
	at java.base/jdk.crac.Core.checkpointRestore(Core.java:271)
	at java.base/jdk.crac.Core.checkpointRestore(Core.java:256)
	at Test.exec(Test.java:83)
	at jdk.test.lib.crac.CracTest.run(CracTest.java:157)
	at jdk.test.lib.crac.CracTest.main(CracTest.java:89)
java.lang.RuntimeException: Checkpointed process was not killed as expected.: expected 137 to equal 1
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertEquals(Asserts.java:205)
	at jdk.test.lib.crac.CracProcess.waitForCheckpointed(CracProcess.java:41)
	at jdk.test.lib.crac.CracBuilder.doCheckpoint(CracBuilder.java:189)
	at jdk.test.lib.crac.CracBuilder.doCheckpointAndRestore(CracBuilder.java:471)
	at Test.test(Test.java:56)
	at jdk.test.lib.crac.CracTest.run(CracTest.java:155)
	at jdk.test.lib.crac.CracTest.main(CracTest.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Checkpointed process was not killed as expected.: expected 137 to equal 1
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Checkpointed process was not killed as expected.: expected 137 to equal 1


```

**Comment by sendaoYan** [comment]
![image](https://github.com/user-attachments/assets/4eb1388c-6ef0-4011-99b6-8dca831cbafa)

**Comment by sendaoYan** [comment]
已修复
