### ISSUE TITLE
[upstream][jdk24][extended-11.0.25.22.9][riscv64]java/net/httpclient/http2/ConnectionReuseTest.java必现java.lang.Exception: JUnit test failure

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#890]
<https://tone.aliyun-inc.com/ws/xesljfzh/test_result/398091?tab=1>   
【环境准备】

```
BINARY_URL=oss://dragonwell/11.0.25.22.9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_11.0.25.22.9_riscv64_linux.tar.gz
TEST_IMAGE=oss://dragonwell/11.0.25.22.9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_11.0.25.22.9_riscv64_linux-testimage.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg-7.3.1.1.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell11.git
JDK_BRANCH=dragonwell_extended-11.0.25.22.9
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev-b  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell11;tar -xf ${BINARY_URL##*/} -C bin-dragonwell11
oss $TEST_IMAGE-l ${TEST_IMAGE##*/}
mkdir images-dragonwell11;tar -xf ${BINARY_URL##*/} -C images-dragonwell11

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo-dragonwell11

执行以下命令：
cd bin-dragonwell11&& export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

jtreg  -nr -v:fail,error -w tmp  -Xmixed  jdk-repo-dragonwell11/test/jdk/java/net/httpclient/http2/ConnectionReuseTest.java
```
【用例日志】  
完整日志：  [ConnectionReuseTest.txt](https://code.alibaba-inc.com/api/v4/projects/2830220/attachment/getViewUrl?fileIdentifier=alibaba/61036/1730875625104ConnectionReuseTest.txt)  
部分日志：

```
FAILED     ConnectionReuseTest::testConnReuse '[2] http://localhost:43215/'
STARTED    ConnectionReuseTest::testConnReuse '[3] http://[::1]:43215/'
TestServer: New connection from Socket[addr=/0:0:0:0:0:0:0:1,port=36114,localport=43215]
TestServer: GET /
Server: creating input stream for stream 1
Using handler for: /
Sent response headers 200
TestServer: GET /
Server: got END_STREAM for stream 3
Using handler for: /
Sent response headers 200
TestServer: GET /
Server: got END_STREAM for stream 5
Using handler for: /
Sent response headers 200
TestServer: GET /
Server: got END_STREAM for stream 7
Using handler for: /
Sent response headers 200
TestServer: GET /
Server: got END_STREAM for stream 9
Using handler for: /
Sent response headers 200
SUCCESSFUL ConnectionReuseTest::testConnReuse '[3] http://[::1]:43215/'
Server stopping 0 connections
Server stopping 1 connections
Server connection to /0:0:0:0:0:0:0:1:36114 stopping. 5 streams
TestServer: Connection writer stopping
JavaTest Message: JUnit Platform Failure(s): 2

[ JUnit Containers: found 5, started 5, succeeded 5, failed 0, aborted 0, skipped 0]
[ JUnit Tests: found 3, started 3, succeeded 1, failed 2, aborted 0, skipped 0]

java.lang.Exception: JUnit test failure
        at com.sun.javatest.regtest.agent.JUnitRunner.runWithJUnitPlatform(JUnitRunner.java:149)
        at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:95)
        at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:955)

```
【jdk信息】

```
java -version;java -Xinternalversion
openjdk version "11.0.25.21" 2024-10-15
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-11.0.24.21+8-ga (build 11.0.25.21+8)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-11.0.24.21+8-ga (build 11.0.25.21+8, mixed mode)
OpenJDK 64-Bit Server VM (11.0.25.21+8) for linux-riscv64 JRE (11.0.25.21+8), built on Nov  4 2024 09:58:16 by "" with gcc 9.2.0
```

【系统版本信息】

```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux fedora-riscv-1 6.1.22 #2 SMP Thu May  4 19:24:40 CST 2023 riscv64 GNU/Linux
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
               total        used        free      shared  buff/cache   available
Mem:            62Gi       1.9Gi        50Gi       9.0Mi        10Gi        60Gi
Swap:          8.0Gi          0B       8.0Gi
Architecture:        riscv64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
NUMA node(s):        4
NUMA node0 CPU(s):   0-7,16-23
NUMA node1 CPU(s):   8-15,24-31
NUMA node2 CPU(s):   32-39,48-55
NUMA node3 CPU(s):   40-47,56-63
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/19054201
