### ISSUE TITLE
[secondary_super_cache][fastdebug][x86_64]-Xcomp -XX:-TieredCompilation选项下com/alibaba/wisp/io/TestDatagramSocket.java报错assertTrue: expected true, was false

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#900]
默认：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/427718    
false：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/427657  
true：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/427676  
【环境准备】

```
BINARY_URL=oss://compiler-ci-bucket/dragonwell11/CI/tar/20241218-003913-968-#597-linux.x86_64.fastdebug.master-b985104eabca8b542fb0e96fb02570b4c4323386.jdk.tar.gz
TEST_IMAGE=oss://compiler-ci-bucket/dragonwell11/CI/tar/20241218-003913-968-#597-linux.x86_64.fastdebug.master-b985104eabca8b542fb0e96fb02570b4c4323386.test-image.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg-7.3.1.1.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell11.git
JDK_BRANCH=master
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev-b  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell11;tar -xf ${BINARY_URL##*/} -C bin-dragonwell11
oss $TEST_IMAGE-l ${TEST_IMAGE##*/}
mkdir images-dragonwell11;tar -xf ${BINARY_URL##*/} -C images-dragonwell11

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo-dragonwell11

执行以下命令：
cd bin-dragonwell11&& export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -
export test=jdk-repo-dragonwell11/test/jdk/com/alibaba/wisp/io/TestDatagramSocket.java

默认：jtreg  -nr -v:fail,error -w tmp   -Xcomp -XX:-TieredCompilation -XX:+UnlockDiagnosticVMOptions  -ea -esa  $test

false：jtreg  -nr -v:fail,error -w tmp   -Xcomp -XX:-TieredCompilation -XX:+UnlockDiagnosticVMOptions -XX:+StressSecondarySupers -XX:+VerifySecondarySupers -ea -esa  $test

true：jtreg  -nr -v:fail,error -w tmp    -Xcomp -XX:-TieredCompilation -XX:+UnlockDiagnosticVMOptions -XX:-InlineSecondarySupersTest -XX:-UseSecondarySupersTable  -XX:-UseSecondarySupersCache -ea -esa $test
```
【对比测试】

```
aarch64和x86_64都失败

默认选项fail
-Xcomp -XX:-TieredCompilation

打开false选项   fail
-Xcomp -XX:-TieredCompilation -XX:+UnlockDiagnosticVMOptions -XX:+StressSecondarySupers -XX:+VerifySecondarySupers

关闭true选项   fail
-Xcomp -XX:-TieredCompilation -XX:+UnlockDiagnosticVMOptions -XX:-InlineSecondarySupersTest -XX:-UseSecondarySupersTable -XX:-UseSecondarySupersCache
```
【用例日志】

```
STDERR:
java.net.SocketTimeoutException: time out
        at java.base/sun.nio.ch.WispUdpSocketImpl.receive0(WispUdpSocketImpl.java:208)
        at java.base/sun.nio.ch.WispUdpSocketImpl.receive(WispUdpSocketImpl.java:137)
        at java.base/sun.nio.ch.WispUdpSocketImpl.receive(WispUdpSocketImpl.java:227)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:779)
        at TestDatagramSocket.lambda$testSendAndReceive$0(TestDatagramSocket.java:73)
        at java.base/java.lang.Thread.run(Thread.java:955)
java.lang.RuntimeException: assertTrue: expected true, was false
        at jdk.testlibrary.Asserts.fail(Asserts.java:540)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
        at TestDatagramSocket.lambda$testSendAndReceive$0(TestDatagramSocket.java:79)
        at java.base/java.lang.Thread.run(Thread.java:955)
STATUS:Failed.`main' threw exception: java.lang.RuntimeException: assertTrue: expected true, was false

```
【jdk信息】

```
java -version;java -Xinternalversion
openjdk version "11.0.25-internal" 2024-10-15
OpenJDK Runtime Environment (fastdebug build 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline)
OpenJDK 64-Bit Server VM (fastdebug build 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline, mixed mode)
OpenJDK 64-Bit Server VM (fastdebug 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline) for linux-amd64 JRE (11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline), built on Dec 17 2024 16:39:47 by "" with gcc 7.5.0
```

【系统版本信息】

```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux CompilerTest-x64-3 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       1.0Gi       112Gi       4.0Mi        10Gi       121Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
Stepping:            6
CPU MHz:             3523.876
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/19777021

**Comment by ziyilin** [comment]
Type pollution的改进不是用选项隔离的特性，测试的对比版本需要用不含该改进的代码编译。比如以https://github.com/dragonwell-project/dragonwell11/commit/c5b54c51bdede891dbbdeaabc72dfda005027cb3 为tip的代码作为对比基线。
编译release版本和fastdebug版本，都执行失败。
失败信息：
```
STDOUT:
Receive buffer size: 106496
Receive buffer size: 32768
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
{cname=CNAME: www.tmall.com.danuoyi.tbcache.com.}
received packets: 18
Average cost is 166.5ms
STDERR:
java.net.SocketTimeoutException: time out
        at java.base/sun.nio.ch.WispUdpSocketImpl.receive0(WispUdpSocketImpl.java:208)
        at java.base/sun.nio.ch.WispUdpSocketImpl.receive(WispUdpSocketImpl.java:137)
        at java.base/sun.nio.ch.WispUdpSocketImpl.receive(WispUdpSocketImpl.java:227)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:779)
        at TestDatagramSocket.lambda$testSendAndReceive$1(TestDatagramSocket.java:77)
        at java.base/java.lang.Thread.run(Thread.java:955)
java.lang.RuntimeException: assertTrue: expected true, was false
        at jdk.testlibrary.Asserts.fail(Asserts.java:540)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:490)
        at jdk.testlibrary.Asserts.assertTrue(Asserts.java:476)
        at TestDatagramSocket.lambda$testSendAndReceive$1(TestDatagramSocket.java:86)
        at java.base/java.lang.Thread.run(Thread.java:955)

```
