### ISSUE TITLE
[secondary_super_cache true][fastdebug]serviceability/sa/CDSJMapClstats.java assert(false) failed: broken secondary supers hash table

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell11#904]
任务链接：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/427763?tab=3  

【环境准备】
```
BINARY_URL=oss://compiler-ci-bucket/dragonwell11/CI/tar/20241218-003913-968-#597-linux.aarch64.fastdebug.master-b985104eabca8b542fb0e96fb02570b4c4323386.jdk.tar.gz
TEST_IMAGE=oss://compiler-ci-bucket/dragonwell11/CI/tar/20241218-003913-968-#597-linux.aarch64.fastdebug.master-b985104eabca8b542fb0e96fb02570b4c4323386.test-image.tar.gz
JVMOPTIONS="-XX:+UnlockDiagnosticVMOptions -XX:-InlineSecondarySupersTest -XX:-UseSecondarySupersTable -XX:-UseSecondarySupersCache"
JDK_REPO=git@github.com:dragonwell-project/dragonwell11.git
JDK_BRANCH=master



#下载解压jtreg，cd jtreg并配置
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
#下载解压jdk，cd <目录>并配置;下载test-image包
export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME
#下载jdk-repo
git clone https://${JDK_REPO} --depth 1 -b $JDK_BRANCH jdk-repo

#执行测试
jtreg -w tmp -nr -v:fail,error -XX:+UnlockDiagnosticVMOptions -XX:-InlineSecondarySupersTest -XX:-UseSecondarySupersTable -XX:-UseSecondarySupersCache serviceability/sa/CDSJMapClstats.java

```   

【测试分析】

```   
aarch64 和x86 在fastdebug 二进制都是fail的，在release都是pass的，secondary_super_cache false 和默认选项都是pass的。

```

【版本信息】     

#jdk信息   
```
openjdk version "11.0.25-internal" 2024-10-15
OpenJDK Runtime Environment (fastdebug build 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline)
OpenJDK 64-Bit Server VM (fastdebug build 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline, mixed mode)
OpenJDK 64-Bit Server VM (fastdebug 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline) for linux-aarch64 JRE (11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline), built on Dec 17 2024 16:39:55 by "" with gcc 7.5.0

```    

#测试机信息jdk环境信息     
```
[root@CompilerTest-aarch64-2 ~]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25; dmidecode -t chassis
Linux CompilerTest-aarch64-2 5.10.134-16.1.al8.aarch64 #1 SMP Thu Dec 7 22:04:51 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          122Gi       1.8Gi       107Gi       1.0Mi        12Gi       119Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Neoverse-N2
BIOS Model name:     virt-rhel7.6.0
Stepping:            r0p0
CPU MHz:             3000.000
CPU max MHz:         3000.0000
CPU min MHz:         3000.0000
BogoMIPS:            100.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            65536K
NUMA node0 CPU(s):   0-31
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x0300, DMI type 3, 21 bytes
Chassis Information
        Manufacturer: Alibaba Cloud
        Type: Other
        Lock: Not Present
        Version: virt-rhel7.6.0
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Boot-up State: Safe
        Power Supply State: Safe
        Thermal State: Safe
        Security Status: Unknown
        OEM Information: 0x00000000
        Height: Unspecified
        Number Of Power Cords: Unspecified
        Contained Elements: 0




```

【用例日志】
```
STDERR:
Command line: ['/root/11/new/j2sdk-image/bin/java' '-XX:+UnlockDiagnosticVMOptions' '-XX:SharedArchiveFile=ArchiveForCDSJMapClstats.jsa' '-Xshare:auto' '-cp' '/root/11/tmp/classes/serviceability/sa/CDSJMapClstats.d:/root/11/tmp/classes/test/lib' 'jdk.test.lib.apps.LingeredApp' '553d93b4-a6a0-4222-987f-13c1e1df7794.lck' ]
LingeredApp failed to start: java.io.IOException: App exited unexpectedly with 134
 LingeredApp stdout: [# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/klass.cpp:392
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/admin/workspace/dragonwell11.nightly.pipeline/src/hotspot/share/oops/klass.cpp:392), pid=3508198, tid=3508201
#  assert(false) failed: broken secondary supers hash table
#
# JRE version:  (11.0.25) (fastdebug build )
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 11.0.25-internal+0-adhoc..dragonwell11.nightly.pipeline, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-aarch64)
# Core dump will be written. Default location: /root/11/tmp/scratch/core.3508198
#
# An error report file with more information is saved as:
# /root/11/tmp/scratch/hs_err_pid3508198.log
#
#
];
 LingeredApp stderr: []
 LingeredApp exitValue = 134
java.lang.RuntimeException: Test ERROR java.io.IOException: App exited unexpectedly with 134
        at CDSJMapClstats.main(CDSJMapClstats.java:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:955)
Caused by: java.io.IOException: App exited unexpectedly with 134
        at jdk.test.lib.apps.LingeredApp.waitAppReady(LingeredApp.java:288)
        at jdk.test.lib.apps.LingeredApp.startApp(LingeredApp.java:442)
        at CDSJMapClstats.main(CDSJMapClstats.java:79)
        ... 6 more

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test ERROR java.io.IOException: App exited unexpectedly with 134
JavaTest Message: shutting down test
```

**Comment by sendaoYan** [comment]
相同的测试命令，主干没有问题

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/19782624

**Comment by ziyilin** [comment]
> `-XX:-UseSecondarySupersTable`选项触发该问题

检查了一下，该jtreg测试分成了两个测试，出问题的是下边的
`/root/11/new/j2sdk-image/bin/java -XX:+UnlockDiagnosticVMOptions -XX:SharedArchiveFile=ArchiveForCDSJMapClstats.jsa -Xshare:auto -cp /root/11/tmp/classes/serviceability/sa/CDSJMapClstats.d:/root/11/tmp/classes/test/lib jdk.test.lib.apps.LingeredApp 553d93b4-a6a0-4222-987f-13c1e1df7794.lck` 
其实是没有`-XX:-UseSecondarySupersTable`选项。

**Comment by sendaoYan** [comment]
已修复合入  
![image](https://github.com/user-attachments/assets/37ca0e68-358c-4e57-9661-04ef9f2a0a4a)
